/// Catalogo de categorias e subcategorias do cadastro de produtos.
abstract final class ProdutoCategoriasCatalogo {
  ProdutoCategoriasCatalogo._();

  static const String outros = 'Outros';

  static const Map<String, List<String>> materiaisConstrucao = {
    'Cimento e Argamassas': ['Cimento', 'Argamassa', 'Rejunte', 'Cal'],
    'Telhas e Cobertura': [
      'Telha Ceramica',
      'Telha Fibrocimento',
      'Telha Metalica',
      'Telha PVC',
      'Cumeeira',
      'Rufos e Calhas',
      'Manta Termica',
      'Parafuso para Telha',
    ],
    'Estrutural e Alvenaria': [
      'Tijolo',
      'Bloco de Concreto',
      'Canaleta',
      'Areia',
      'Brita',
      'Pedra',
      'Aco para Construcao',
      'Vergalhao',
    ],
    'Tintas e Acessorios': [
      'Tinta Acrilica',
      'Tinta Esmalte',
      'Selador',
      'Verniz',
      'Rolo e Pincel',
    ],
    'Hidraulica': [
      'Tubos e Conexoes',
      'Registros',
      'Torneiras',
      'Caixa d\'agua',
      'Sifoes e Valvulas',
      'Bombas',
      'Irrigacao',
      'Acessorios para Banheiro',
    ],
    'Eletrica': [
      'Fios e Cabos',
      'Disjuntores',
      'Tomadas e Interruptores',
      'Quadro de Distribuicao',
      'Iluminacao',
      'Eletroduto',
      'Canaleta',
      'Luminaria LED',
    ],
    'Ferragens': [
      'Parafusos e Buchas',
      'Pregos',
      'Dobradiças',
      'Fechaduras',
      'Correntes e Cabos de Aco',
      'Abraçadeiras',
      'Chapas e Cantoneiras',
      'Fixadores',
    ],
    'Madeiras e Chapas': [
      'Compensado',
      'MDF',
      'OSB',
      'Vigas e Ripas',
      'Portas e Batentes',
    ],
    'Pisos e Revestimentos': [
      'Piso Ceramico',
      'Porcelanato',
      'Revestimento de Parede',
      'Rodape',
      'Pastilha',
    ],
    'Loucas e Metais': [
      'Vaso Sanitario',
      'Lavatório',
      'Cuba',
      'Torneira',
      'Chuveiro',
      'Misturador',
      'Assento Sanitario',
    ],
    'Impermeabilizacao e Quimicos': [
      'Impermeabilizante',
      'Vedante',
      'Silicone',
      'Espuma Expansiva',
      'Aditivo para Concreto',
      'Desmoldante',
    ],
    'Ferramentas': [
      'Manuais',
      'Eletricas',
      'Medicao',
      'EPIs',
      'Acessorios de Corte',
    ],
    'Jardinagem e Externo': [
      'Mangueira',
      'Grama Sintetica',
      'Ferramentas de Jardim',
      'Vaso e Cachepot',
      'Pedrisco Decorativo',
    ],
    'Forros e Divisorias': [
      'Forro PVC',
      'Forro Gesso',
      'Perfil para Drywall',
      'Chapa Drywall',
      'Acessorios Drywall',
    ],
    outros: [],
  };
}
