/// Setor da loja usado para agrupar categorias na selecao.
class ProdutoCategoriaSetor {
  const ProdutoCategoriaSetor({
    required this.nome,
    required this.categorias,
  });

  final String nome;
  final List<String> categorias;
}

/// Catalogo de categorias e subcategorias do cadastro de produtos.
abstract final class ProdutoCategoriasCatalogo {
  ProdutoCategoriasCatalogo._();

  static const String outros = 'Outros';

  static const Map<String, List<String>> materiaisConstrucao = {
    'Cimento e Argamassas': [
      'Cimento',
      'Argamassa',
      'Rejunte',
      'Cal',
      'Argamassa Colante',
      'Gesso em Po',
      'Graute',
      'Chapisco',
      'Concreto',
      'Contrapiso',
      'Autonivelante e Nivelador',
      'Cimento Queimado',
      'Massa para Assentamento',
      'Revestimento Acrilico',
      'Aditivo para Argamassa',
      'Pigmento para Concreto',
    ],
    'Telhas e Cobertura': [
      'Telha Ceramica',
      'Telha Fibrocimento',
      'Telha Metalica',
      'Telha PVC',
      'Cumeeira',
      'Rufos e Calhas',
      'Manta Termica',
      'Parafuso para Telha',
      'Telha de Concreto',
      'Telha Translucida',
      'Espigao',
      'Telha Shingle',
      'Clarabola e Domus',
      'Madeiramento e Caibros',
      'Calha e Condutor Pluvial',
      'Acessorios de Cobertura',
    ],
    'Estrutural e Alvenaria': [
      'Tijolo',
      'Bloco de Concreto',
      'Canaleta',
      'Areia',
      'Brita',
      'Pedra',
      'Aco para Construcao',
      'Vergalhao',
      'Bloco Ceramico',
      'Laje e Trelica',
      'Arame Recozido',
      'Po de Pedra',
      'Tela para Concreto',
      'Forma para Concreto',
      'Escora e Andaime',
      'Estribo e Ferragem Pronta',
      'Cascalho e Pedrisco',
      'Tela eletrossoldada',
      'Grampos para Ferragem',
    ],
    'Tintas e Acessorios': [
      'Tinta Acrilica',
      'Tinta Esmalte',
      'Selador',
      'Verniz',
      'Rolo e Pincel',
      'Massa Corrida',
      'Massa Acrilica',
      'Textura',
      'Fundo Preparador',
      'Tinta para Piso',
      'Tinta Epoxi',
      'Spray',
      'Solvente e Thinner',
      'Tinta Latex PVA',
      'Tinta Anti-mofo',
      'Tinta Automotiva',
      'Tinta para Madeira',
      'Removedor e Diluente',
      'Bandeja e Extensor de Pintura',
      'Stucco e Grafiato',
    ],
    'Hidraulica': [
      'Tubos e Conexoes',
      'Registros',
      'Torneiras',
      'Caixa d\'agua',
      'Sifoes e Valvulas',
      'Bombas',
      'Irrigacao',
      'Acessorios para Banheiro',
      'Tubo de Esgoto',
      'Agua Quente (CPVC e PPR)',
      'Caixa de Gordura',
      'Ralos e Grelhas',
      'Valvula de Descarga',
      'Flexiveis e Engates',
      'Filtros e Purificadores',
      'Boia e Valvula Boia',
      'Mecanismo de Descarga',
      'Vedacao Hidraulica (Anel e Teflon)',
      'Chuveiro e Ducha Eletrica',
      'Barra de Apoio e Acessibilidade',
      'Hidrometro e Cavalete',
      'Drenagem Pluvial',
      'Misturador de Pia',
    ],
    'Eletrica': [
      'Fios e Cabos',
      'Disjuntores',
      'Tomadas e Interruptores',
      'Quadro de Distribuicao',
      'Iluminacao',
      'Eletroduto',
      'Canaleta',
      'Luminaria LED',
      'Fita Isolante',
      'Conectores e Emendas',
      'DR e DPS',
      'Caixa de Passagem',
      'Eletrocalha',
      'Extensao e Plugue',
      'Sensores e Campainhas',
      'Automacao Residencial',
      'Cabos de Comando e Telefonia',
      'Steck e Plug Macho/Femea',
      'Organizador e Abraçadeira de Cabo',
      'Chuveiro Eletrico (Resistencia)',
      'Fonte e Transformador',
      'Timer e Rele',
      'Motor de Portao',
    ],
    'Ferragens': [
      'Parafusos e Buchas',
      'Pregos',
      'Dobradiças',
      'Fechaduras',
      'Correntes e Cabos de Aco',
      'Abraçadeiras',
      'Chapas e Cantoneiras',
      'Fixadores',
      'Puxadores e Macanetas',
      'Cadeados',
      'Porcas e Arruelas',
      'Rebites',
      'Arames e Grampos',
      'Suportes e Ganchos',
      'Ferragens para Moveis',
      'Corrediça e Trilho',
      'Rodizio e Roda',
      'Ferragens para Box e Vidro',
      'Fechadura Eletronica',
      'Parafuso Autoperfurante',
      'Cantoneira Decorativa',
      'Pino e Trava',
    ],
    'Madeiras e Chapas': [
      'Compensado',
      'MDF',
      'OSB',
      'Vigas e Ripas',
      'Portas e Batentes',
      'Sarrafo e Caibro',
      'Tabua',
      'Deck',
      'MDP',
      'Chapa Naval',
      'Madeira Plastica e WPC',
      'Eucalipto Tratado',
      'Tapume e Forma',
      'Fita de Borda',
      'Compensado Naval',
    ],
    'Pisos e Revestimentos': [
      'Piso Ceramico',
      'Porcelanato',
      'Revestimento de Parede',
      'Rodape',
      'Pastilha',
      'Piso Vinilico',
      'Piso Laminado',
      'Piso Intertravado',
      'Pedra Natural',
      'Soleira e Peitoril',
      'Espacador de Piso',
      'Carpete e Tapete',
      'Taco e Assoalho',
      'Piso Emborrachado',
      'Deck e WPC',
      'Nivelador de Piso',
      'Piso Antiderrapante',
      'Filete e Cantoneira de Acabamento',
    ],
    'Loucas e Metais': [
      'Vaso Sanitario',
      'Lavatório',
      'Cuba',
      'Torneira',
      'Chuveiro',
      'Misturador',
      'Assento Sanitario',
      'Pia de Cozinha',
      'Tanque',
      'Banheira',
      'Ducha Higienica',
      'Caixa Acoplada',
      'Acessorios de Banheiro',
      'Ralo Linear',
      'Bide',
      'Urinol',
      'Coifa e Exaustor de Cozinha',
      'Torneira Gourmet e Filtro',
      'Complementos WC e Fixacao',
      'Pia de Banheiro',
    ],
    'Impermeabilizacao e Quimicos': [
      'Impermeabilizante',
      'Vedante',
      'Silicone',
      'Espuma Expansiva',
      'Aditivo para Concreto',
      'Desmoldante',
      'Manta Asfaltica',
      'Manta Liquida',
      'Primer Asfaltico',
      'Tela de Poliester',
      'Hidrofugante',
      'Membrana e Mantas',
      'Impermeabilizante para Laje',
      'Protetor de Superficie',
      'PU e Selante Poliuretano',
    ],
    'Ferramentas': [
      'Manuais',
      'Eletricas',
      'Medicao',
      'EPIs',
      'Acessorios de Corte',
      'Pneumaticas',
      'Escadas',
      'Carrinho de Mao',
      'Betoneira',
      'Ferramentas de Pedreiro',
      'Alicates e Chaves',
      'Serrote e Serra Manual',
      'Corta-Vidro',
      'Nivel e Prumo',
      'Furadeira e Parafusadeira',
      'Compressor e Gerador',
      'Aspirador de Obra',
      'Macaco e Guincho',
      'Cinta e Talha',
    ],
    'Jardinagem e Externo': [
      'Mangueira',
      'Grama Sintetica',
      'Ferramentas de Jardim',
      'Vaso e Cachepot',
      'Pedrisco Decorativo',
      'Terra e Substrato',
      'Adubo',
      'Regador e Aspersor',
      'Irrigacao de Jardim',
      'Rocha Ornamental',
      'Defensivo Agricola',
      'Composteira',
      'Poda e Podador',
      'Cerca e Arame para Jardim',
      'Iluminacao Solar Externa',
    ],
    'Forros e Divisorias': [
      'Forro PVC',
      'Forro Gesso',
      'Perfil para Drywall',
      'Chapa Drywall',
      'Acessorios Drywall',
      'Forro Mineral',
      'Forro de Isopor',
      'Lambri',
      'Perfil de Aluminio',
      'Perfil de Acabamento',
      'Raguardo e Guia',
      'Divisoria e Eucatex',
    ],
    'Portas, Janelas e Vidros': [
      'Porta de Madeira',
      'Porta de Aluminio',
      'Porta Sanfonada',
      'Janela',
      'Basculante',
      'Vidro',
      'Espelho',
      'Box para Banheiro',
      'Grade e Portao',
      'Porta de Ferro e Aco',
      'Persiana e Veneziana',
      'Kit Portao e Correr',
      'Cortina de PVC',
      'Ferragens para Porta e Janela',
    ],
    'Iluminacao': [
      'Lampada',
      'Luminaria',
      'Refletor',
      'Painel de LED',
      'Spot e Embutido',
      'Fita de LED',
      'Plafon e Arandela',
      'Soquete e Reator',
      'Poste e Braco de Iluminacao',
      'Iluminacao Externa e Jardim',
      'Emergencia e Balizamento',
      'Lustre e Pendente',
    ],
    'Climatizacao': [
      'Ventilador',
      'Exaustor',
      'Ar Condicionado',
      'Aquecedor',
      'Ventilador de Teto',
      'Climatizador Evaporativo',
      'Umidificador e Desumidificador',
      'Ducto e Grelha de Ventilacao',
      'Insuflador',
    ],
    'Abrasivos e Corte': [
      'Lixa',
      'Disco de Corte',
      'Disco de Desbaste',
      'Broca',
      'Serra Copo',
      'Eletrodo de Solda',
      'Disco Flap e Laminado',
      'Serra Circular e Lamina',
      'Rebolo e Retifica',
      'Manta Abrasiva',
      'Serra Tico-Tico',
    ],
    'Colas, Fitas e Vedacao': [
      'Cola Branca e de Madeira',
      'Adesivo Instantaneo',
      'Fita Crepe',
      'Fita Veda Rosca',
      'Fita Dupla Face',
      'Massa de Vedacao',
      'Cola Contact',
      'Cola para Porcelanato',
      'Fita Aluminio e Silver Tape',
      'Adesivo de Montagem',
      'Rejunte Liquido e Grout',
    ],
    'EPIs e Seguranca': [
      'Capacete',
      'Luva',
      'Oculos de Protecao',
      'Bota de Seguranca',
      'Mascara e Respirador',
      'Protetor Auricular',
      'Cinto de Seguranca',
      'Sinalizacao de Obra',
      'Mangote e Avental',
      'Cone e Fita Zebrada',
      'Extintor',
      'Kit Primeiros Socorros',
      'Creme Protetor',
    ],
    'Telas, Cercas e Alambrados': [
      'Tela Soldada',
      'Alambrado',
      'Tela Mosquiteiro',
      'Arame Farpado',
      'Mourao',
      'Concertina',
      'Portao de Alambrado',
      'Grade de Protecao',
      'Tela Galinheiro',
      'Cerca Eletrica',
    ],
    'Gas e Aquecimento': [
      'Botijao e GLP',
      'Regulador e Mangueira de Gas',
      'Fogao e Fogao de Campo',
      'Churrasqueira e Grelha',
      'Queimador e Pedra para Churrasqueira',
      'Forno a Lenha e Rotisserie',
      'Aquecedor a Gas',
      'Valvula e Registro de Gas',
      'Fogao Industrial e Queimador',
    ],
    'Isolamento Termico e Acustico': [
      'La de Vidro',
      'La de Rocha',
      'EPS e Isopor em Placa',
      'Manta Termo-Acustica',
      'Isolamento para Tubos',
      'Barreira de Vapor',
      'Painel Sandwich',
      'Espuma Expansiva Isolante',
    ],
    'Premoldados e Concreto': [
      'Meio-fio e Guia',
      'Bloco Decorativo e Paver',
      'Canaleta e Grelha de Concreto',
      'Poste e Mourao de Concreto',
      'Placa de Concreto',
      'Viga Pre-moldada',
      'Anel de Concreto',
      'Tampa de Caixa e Grelha',
    ],
    'Fixacao Quimica e Ancoragem': [
      'Chumbador Quimico',
      'Bucha de Expansao',
      'Parafuso de Ancoragem',
      'Cinta de Amarracao',
      'Separador de Ferragem',
      'Chumbador de Expansion',
      'Resina e Catalisador',
    ],
    'Soldagem e Metais': [
      'Eletrodo e Arame de Solda',
      'Maquina de Solda',
      'Maçarico e Solda Oxi',
      'Perfil Metalico',
      'Chapa de Aco',
      'Tubo Metalico',
      'Cantoneira e Perfil U',
      'Tela Expandida',
    ],
    'Automacao, Seguranca e Telecom': [
      'Camera e DVR',
      'Alarme e Sensor',
      'Video Porteiro e Interfone',
      'Cabo de Rede e Coaxial',
      'Antena e Suporte',
      'Roteador e Acessorios de Rede',
      'Controle de Acesso',
      'Central de Automacao',
    ],
    'Moveis e Decoracao': [
      'Moveis Prontos',
      'Cortina e Persiana',
      'Tapete e Capacho',
      'Quadro e Moldura',
      'Adesivo Decorativo',
      'Prateleira e Estante',
      'Organizador de Ambiente',
    ],
    'Casa, Limpeza e Utilidades': [
      'Produtos de Limpeza',
      'Descartaveis e Embalagens',
      'Utensilios Domesticos',
      'Organizacao e Aramados',
      'Varal e Secagem',
      'Inseticida e Repelente',
      'Papel Higienico e Absorvente',
      'Lixeira e Saco de Lixo',
    ],
    'Piscina e Lazer': [
      'Piscina e Cascata',
      'Tratamento de Piscina',
      'Aspirador e Acessorios de Piscina',
      'Guarda-sol e Ombrelone',
      'Espreguiçadeira e Cadeira',
      'Hidromassagem e Spa',
      'Brinquedo de Piscina',
    ],
    outros: [],
  };

  static const List<ProdutoCategoriaSetor> setores = [
    ProdutoCategoriaSetor(
      nome: 'Obra bruta',
      categorias: [
        'Cimento e Argamassas',
        'Estrutural e Alvenaria',
        'Telhas e Cobertura',
        'Impermeabilizacao e Quimicos',
        'Forros e Divisorias',
        'Premoldados e Concreto',
        'Isolamento Termico e Acustico',
        'Fixacao Quimica e Ancoragem',
      ],
    ),
    ProdutoCategoriaSetor(
      nome: 'Acabamento',
      categorias: [
        'Tintas e Acessorios',
        'Pisos e Revestimentos',
        'Loucas e Metais',
        'Madeiras e Chapas',
        'Portas, Janelas e Vidros',
        'Moveis e Decoracao',
      ],
    ),
    ProdutoCategoriaSetor(
      nome: 'Instalacoes',
      categorias: [
        'Hidraulica',
        'Eletrica',
        'Iluminacao',
        'Climatizacao',
        'Gas e Aquecimento',
        'Automacao, Seguranca e Telecom',
      ],
    ),
    ProdutoCategoriaSetor(
      nome: 'Ferragens e ferramentas',
      categorias: [
        'Ferragens',
        'Ferramentas',
        'Abrasivos e Corte',
        'Colas, Fitas e Vedacao',
        'EPIs e Seguranca',
        'Telas, Cercas e Alambrados',
        'Soldagem e Metais',
      ],
    ),
    ProdutoCategoriaSetor(
      nome: 'Area externa',
      categorias: [
        'Jardinagem e Externo',
        'Piscina e Lazer',
      ],
    ),
    ProdutoCategoriaSetor(
      nome: 'Casa e utilidades',
      categorias: [
        'Casa, Limpeza e Utilidades',
      ],
    ),
    ProdutoCategoriaSetor(
      nome: 'Geral',
      categorias: [outros],
    ),
  ];

  /// Nomes curtos ou de sistemas legados que apontam para uma categoria.
  static const Map<String, String> aliases = {
    'hidraulico': 'Hidraulica',
    'eletrico': 'Eletrica',
    'tintas': 'Tintas e Acessorios',
    'cimento': 'Cimento e Argamassas',
    'argamassa': 'Cimento e Argamassas',
    'telhas': 'Telhas e Cobertura',
    'cobertura': 'Telhas e Cobertura',
    'alvenaria': 'Estrutural e Alvenaria',
    'estrutural': 'Estrutural e Alvenaria',
    'madeiras': 'Madeiras e Chapas',
    'pisos': 'Pisos e Revestimentos',
    'revestimentos': 'Pisos e Revestimentos',
    'loucas': 'Loucas e Metais',
    'metais': 'Loucas e Metais',
    'impermeabilizacao': 'Impermeabilizacao e Quimicos',
    'quimicos': 'Impermeabilizacao e Quimicos',
    'jardinagem': 'Jardinagem e Externo',
    'forros': 'Forros e Divisorias',
    'drywall': 'Forros e Divisorias',
    'portas': 'Portas, Janelas e Vidros',
    'janelas': 'Portas, Janelas e Vidros',
    'vidros': 'Portas, Janelas e Vidros',
    'iluminacao': 'Iluminacao',
    'lampadas': 'Iluminacao',
    'climatizacao': 'Climatizacao',
    'abrasivos': 'Abrasivos e Corte',
    'colas': 'Colas, Fitas e Vedacao',
    'fitas': 'Colas, Fitas e Vedacao',
    'epis': 'EPIs e Seguranca',
    'seguranca': 'EPIs e Seguranca',
    'cercas': 'Telas, Cercas e Alambrados',
    'alambrados': 'Telas, Cercas e Alambrados',
    'telas': 'Telas, Cercas e Alambrados',
    'gas': 'Gas e Aquecimento',
    'glp': 'Gas e Aquecimento',
    'churrasqueira': 'Gas e Aquecimento',
    'isolamento': 'Isolamento Termico e Acustico',
    'termico': 'Isolamento Termico e Acustico',
    'acustico': 'Isolamento Termico e Acustico',
    'premoldados': 'Premoldados e Concreto',
    'concreto': 'Premoldados e Concreto',
    'ancoragem': 'Fixacao Quimica e Ancoragem',
    'chumbador': 'Fixacao Quimica e Ancoragem',
    'soldagem': 'Soldagem e Metais',
    'solda': 'Soldagem e Metais',
    'automacao': 'Automacao, Seguranca e Telecom',
    'telecom': 'Automacao, Seguranca e Telecom',
    'camera': 'Automacao, Seguranca e Telecom',
    'moveis': 'Moveis e Decoracao',
    'decoracao': 'Moveis e Decoracao',
    'limpeza': 'Casa, Limpeza e Utilidades',
    'utilidades': 'Casa, Limpeza e Utilidades',
    'piscina': 'Piscina e Lazer',
    'lazer': 'Piscina e Lazer',
  };

  static List<String> subcategoriasDe(String? categoria) =>
      materiaisConstrucao[categoria] ?? const [];

  static String? setorDe(String? categoria) {
    if (categoria == null || categoria.trim().isEmpty) return null;
    for (final setor in setores) {
      if (setor.categorias.contains(categoria)) return setor.nome;
    }
    return null;
  }

  static String? resolverCategoria(String bruto) {
    final texto = bruto.trim();
    if (texto.isEmpty) return null;
    if (materiaisConstrucao.containsKey(texto)) return texto;
    final n = normalizar(texto);
    if (n.isEmpty) return null;
    final alias = aliases[n];
    if (alias != null && materiaisConstrucao.containsKey(alias)) return alias;
    for (final key in materiaisConstrucao.keys) {
      if (normalizar(key) == n) return key;
    }
    return null;
  }

  static String normalizar(String s) => s
      .toLowerCase()
      .replaceAll(RegExp(r'[áàâãä]'), 'a')
      .replaceAll(RegExp(r'[éèêë]'), 'e')
      .replaceAll(RegExp(r'[íìîï]'), 'i')
      .replaceAll(RegExp(r'[óòôõö]'), 'o')
      .replaceAll(RegExp(r'[úùûü]'), 'u')
      .replaceAll(RegExp(r'[ç]'), 'c')
      .replaceAll(RegExp(r'[^a-z0-9]'), '');

  static String textoParaPrompt() {
    final buf = StringBuffer(
      'Catalogo da loja — use categoria_sugerida e subcategoria_sugerida '
      'com o texto EXATO de uma opcao abaixo:\n',
    );
    for (final setor in setores) {
      buf.writeln('Setor ${setor.nome}:');
      for (final cat in setor.categorias) {
        if (cat == outros) continue;
        final subs = materiaisConstrucao[cat] ?? const <String>[];
        if (subs.isEmpty) continue;
        buf.writeln('- $cat: ${subs.join(' | ')}');
      }
    }
    return buf.toString();
  }
}
