// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'model/cliente.dart';
import 'model/item_venda.dart';
import 'model/produto.dart';
import 'model/venda.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 805574422642691043),
    name: 'ItemVenda',
    lastPropertyId: const obx_int.IdUid(8, 4668469838628667719),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2844102084704375443),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2558730134591822875),
        name: 'quantidade',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1217395620768445493),
        name: 'precoUnitario',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4432181740490742128),
        name: 'produtoId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(1, 3416570875771764023),
        relationField: 'produto',
        relationTarget: 'Produto',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 1892429704353673689),
        name: 'vendaId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(2, 1007099967024991476),
        relationField: 'venda',
        relationTarget: 'Venda',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 6701956797859389788),
        name: 'nomeProduto',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 7921971802503083893),
        name: 'precoCustoUnitario',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 4668469838628667719),
        name: 'precoTipo',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 12069401530715107),
    name: 'Produto',
    lastPropertyId: const obx_int.IdUid(23, 4928394063071914210),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6845762842088825305),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8766242792253639911),
        name: 'nome',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3014136920685238834),
        name: 'estoque',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7112622695991261288),
        name: 'precoCusto',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6136892366305375888),
        name: 'precoVenda',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 8198160407953380318),
        name: 'criadoEm',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 7930730832698641369),
        name: 'quantidadeMinima',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 4671123828913692338),
        name: 'codigoInterno',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 7692428431208033005),
        name: 'descricao',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 3014708834110749898),
        name: 'unidade',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 6060727120274258032),
        name: 'categoria',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 2904582454658343626),
        name: 'subcategoria',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 3028419417235337371),
        name: 'marca',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 8220153953280622826),
        name: 'fornecedor',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 6843794985607382992),
        name: 'fabricante',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 2717273193349575761),
        name: 'codigoBarras',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(17, 3697983639399962673),
        name: 'localizacao',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(18, 3087462972484931213),
        name: 'ncm',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(20, 4384449226668016299),
        name: 'fotoPath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(21, 4705565524302891427),
        name: 'preco1',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(22, 2856288256615956036),
        name: 'preco2',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(23, 4928394063071914210),
        name: 'preco3',
        type: 8,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 1373149988303506096),
    name: 'Venda',
    lastPropertyId: const obx_int.IdUid(16, 7685998874231786707),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3054998435758771479),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 9148258983918137274),
        name: 'data',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6039271794964740472),
        name: 'total',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8005448189673274687),
        name: 'custoTotal',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 1561233662105521358),
        name: 'lucroTotal',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 3487146687259899031),
        name: 'cancelada',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 9036576713029794994),
        name: 'status',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 5888505887334690258),
        name: 'numeroOrcamento',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 5228539885091922933),
        name: 'formaPagamento',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 3562657315709897588),
        name: 'quantidadeParcelas',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 5139057823397078840),
        name: 'clienteId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(3, 4584164524797729456),
        relationField: 'cliente',
        relationTarget: 'Cliente',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 3131322751820763613),
        name: 'tipoEntrega',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 2999771205042016440),
        name: 'valorFrete',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 8042255218919570048),
        name: 'enderecoEntrega',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 8422240493862704459),
        name: 'observacaoEntrega',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 7685998874231786707),
        name: 'statusEntrega',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'itens',
        srcEntity: 'ItemVenda',
        srcField: 'venda',
      ),
    ],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 8923372746033765628),
    name: 'Cliente',
    lastPropertyId: const obx_int.IdUid(20, 6486430712394977568),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 890861945693633328),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6553881396131161790),
        name: 'tipoPessoa',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5724585618422995633),
        name: 'nomeRazao',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6143058838078556321),
        name: 'nomeFantasia',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 1179106941222261668),
        name: 'documento',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 8725588667688515569),
        name: 'inscricaoEstadual',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 3449271875040642616),
        name: 'telefone',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 4873452929797137508),
        name: 'whatsapp',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 8018106346336043925),
        name: 'email',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 8902294221741944013),
        name: 'cep',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 467815795108994607),
        name: 'endereco',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 4590892111661655236),
        name: 'numero',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 271737529434947332),
        name: 'bairro',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 3517125582596044450),
        name: 'cidade',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 8648437437100286039),
        name: 'uf',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 4134087706641037077),
        name: 'referencia',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(17, 2981032616131028380),
        name: 'limiteCredito',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(18, 6022032322724880616),
        name: 'observacoes',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(19, 5153641913998207152),
        name: 'ativo',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(20, 6486430712394977568),
        name: 'criadoEm',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(4, 8923372746033765628),
    lastIndexId: const obx_int.IdUid(3, 4584164524797729456),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [8694161291238035285],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    ItemVenda: obx_int.EntityDefinition<ItemVenda>(
      model: _entities[0],
      toOneRelations: (ItemVenda object) => [object.produto, object.venda],
      toManyRelations: (ItemVenda object) => {},
      getId: (ItemVenda object) => object.id,
      setId: (ItemVenda object, int id) {
        object.id = id;
      },
      objectToFB: (ItemVenda object, fb.Builder fbb) {
        final nomeProdutoOffset = fbb.writeString(object.nomeProduto);
        final precoTipoOffset = fbb.writeString(object.precoTipo);
        fbb.startTable(9);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.quantidade);
        fbb.addFloat64(2, object.precoUnitario);
        fbb.addInt64(3, object.produto.targetId);
        fbb.addInt64(4, object.venda.targetId);
        fbb.addOffset(5, nomeProdutoOffset);
        fbb.addFloat64(6, object.precoCustoUnitario);
        fbb.addOffset(7, precoTipoOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final nomeProdutoParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final quantidadeParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final precoTipoParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 18, '');
        final precoUnitarioParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final precoCustoUnitarioParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final object = ItemVenda(
          id: idParam,
          nomeProduto: nomeProdutoParam,
          quantidade: quantidadeParam,
          precoTipo: precoTipoParam,
          precoUnitario: precoUnitarioParam,
          precoCustoUnitario: precoCustoUnitarioParam,
        );
        object.produto.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        object.produto.attach(store);
        object.venda.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        object.venda.attach(store);
        return object;
      },
    ),
    Produto: obx_int.EntityDefinition<Produto>(
      model: _entities[1],
      toOneRelations: (Produto object) => [],
      toManyRelations: (Produto object) => {},
      getId: (Produto object) => object.id,
      setId: (Produto object, int id) {
        object.id = id;
      },
      objectToFB: (Produto object, fb.Builder fbb) {
        final nomeOffset = fbb.writeString(object.nome);
        final codigoInternoOffset = fbb.writeString(object.codigoInterno);
        final descricaoOffset = fbb.writeString(object.descricao);
        final unidadeOffset = fbb.writeString(object.unidade);
        final categoriaOffset = fbb.writeString(object.categoria);
        final subcategoriaOffset = fbb.writeString(object.subcategoria);
        final marcaOffset = fbb.writeString(object.marca);
        final fornecedorOffset = fbb.writeString(object.fornecedor);
        final fabricanteOffset = fbb.writeString(object.fabricante);
        final codigoBarrasOffset = fbb.writeString(object.codigoBarras);
        final localizacaoOffset = fbb.writeString(object.localizacao);
        final ncmOffset = fbb.writeString(object.ncm);
        final fotoPathOffset = fbb.writeString(object.fotoPath);
        fbb.startTable(24);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nomeOffset);
        fbb.addInt64(2, object.estoque);
        fbb.addFloat64(3, object.precoCusto);
        fbb.addFloat64(4, object.precoVenda);
        fbb.addInt64(5, object.criadoEm.millisecondsSinceEpoch);
        fbb.addInt64(6, object.quantidadeMinima);
        fbb.addOffset(7, codigoInternoOffset);
        fbb.addOffset(8, descricaoOffset);
        fbb.addOffset(9, unidadeOffset);
        fbb.addOffset(10, categoriaOffset);
        fbb.addOffset(11, subcategoriaOffset);
        fbb.addOffset(12, marcaOffset);
        fbb.addOffset(13, fornecedorOffset);
        fbb.addOffset(14, fabricanteOffset);
        fbb.addOffset(15, codigoBarrasOffset);
        fbb.addOffset(16, localizacaoOffset);
        fbb.addOffset(17, ncmOffset);
        fbb.addOffset(19, fotoPathOffset);
        fbb.addFloat64(20, object.preco1);
        fbb.addFloat64(21, object.preco2);
        fbb.addFloat64(22, object.preco3);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final codigoInternoParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 18, '');
        final nomeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final descricaoParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 20, '');
        final unidadeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 22, '');
        final categoriaParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 24, '');
        final subcategoriaParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 26, '');
        final marcaParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 28, '');
        final fornecedorParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 30, '');
        final fabricanteParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 32, '');
        final codigoBarrasParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 34, '');
        final fotoPathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 42, '');
        final localizacaoParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 36, '');
        final ncmParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 38, '');
        final estoqueParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final quantidadeMinimaParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final precoCustoParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final preco1Param = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          44,
          0,
        );
        final preco2Param = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          46,
          0,
        );
        final preco3Param = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          48,
          0,
        );
        final precoVendaParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final criadoEmParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0),
          isUtc: true,
        );
        final object = Produto(
          id: idParam,
          codigoInterno: codigoInternoParam,
          nome: nomeParam,
          descricao: descricaoParam,
          unidade: unidadeParam,
          categoria: categoriaParam,
          subcategoria: subcategoriaParam,
          marca: marcaParam,
          fornecedor: fornecedorParam,
          fabricante: fabricanteParam,
          codigoBarras: codigoBarrasParam,
          fotoPath: fotoPathParam,
          localizacao: localizacaoParam,
          ncm: ncmParam,
          estoque: estoqueParam,
          quantidadeMinima: quantidadeMinimaParam,
          precoCusto: precoCustoParam,
          preco1: preco1Param,
          preco2: preco2Param,
          preco3: preco3Param,
          precoVenda: precoVendaParam,
          criadoEm: criadoEmParam,
        );

        return object;
      },
    ),
    Venda: obx_int.EntityDefinition<Venda>(
      model: _entities[2],
      toOneRelations: (Venda object) => [object.cliente],
      toManyRelations: (Venda object) => {
        obx_int.RelInfo<ItemVenda>.toOneBacklink(
          5,
          object.id,
          (ItemVenda srcObject) => srcObject.venda,
        ): object.itens,
      },
      getId: (Venda object) => object.id,
      setId: (Venda object, int id) {
        object.id = id;
      },
      objectToFB: (Venda object, fb.Builder fbb) {
        final statusOffset = fbb.writeString(object.status);
        final formaPagamentoOffset = fbb.writeString(object.formaPagamento);
        final tipoEntregaOffset = fbb.writeString(object.tipoEntrega);
        final enderecoEntregaOffset = fbb.writeString(object.enderecoEntrega);
        final observacaoEntregaOffset = fbb.writeString(
          object.observacaoEntrega,
        );
        final statusEntregaOffset = fbb.writeString(object.statusEntrega);
        fbb.startTable(17);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.data.millisecondsSinceEpoch);
        fbb.addFloat64(2, object.total);
        fbb.addFloat64(3, object.custoTotal);
        fbb.addFloat64(4, object.lucroTotal);
        fbb.addBool(5, object.cancelada);
        fbb.addOffset(6, statusOffset);
        fbb.addInt64(7, object.numeroOrcamento);
        fbb.addOffset(8, formaPagamentoOffset);
        fbb.addInt64(9, object.quantidadeParcelas);
        fbb.addInt64(10, object.cliente.targetId);
        fbb.addOffset(11, tipoEntregaOffset);
        fbb.addFloat64(12, object.valorFrete);
        fbb.addOffset(13, enderecoEntregaOffset);
        fbb.addOffset(14, observacaoEntregaOffset);
        fbb.addOffset(15, statusEntregaOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final dataParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0),
          isUtc: true,
        );
        final totalParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final custoTotalParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final lucroTotalParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final statusParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final numeroOrcamentoParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        final formaPagamentoParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 20, '');
        final quantidadeParcelasParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          22,
          0,
        );
        final tipoEntregaParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 26, '');
        final valorFreteParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          28,
          0,
        );
        final enderecoEntregaParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 30, '');
        final observacaoEntregaParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 32, '');
        final statusEntregaParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 34, '');
        final canceladaParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          14,
          false,
        );
        final object = Venda(
          id: idParam,
          data: dataParam,
          total: totalParam,
          custoTotal: custoTotalParam,
          lucroTotal: lucroTotalParam,
          status: statusParam,
          numeroOrcamento: numeroOrcamentoParam,
          formaPagamento: formaPagamentoParam,
          quantidadeParcelas: quantidadeParcelasParam,
          tipoEntrega: tipoEntregaParam,
          valorFrete: valorFreteParam,
          enderecoEntrega: enderecoEntregaParam,
          observacaoEntrega: observacaoEntregaParam,
          statusEntrega: statusEntregaParam,
          cancelada: canceladaParam,
        );
        object.cliente.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          24,
          0,
        );
        object.cliente.attach(store);
        obx_int.InternalToManyAccess.setRelInfo<Venda>(
          object.itens,
          store,
          obx_int.RelInfo<ItemVenda>.toOneBacklink(
            5,
            object.id,
            (ItemVenda srcObject) => srcObject.venda,
          ),
        );
        return object;
      },
    ),
    Cliente: obx_int.EntityDefinition<Cliente>(
      model: _entities[3],
      toOneRelations: (Cliente object) => [],
      toManyRelations: (Cliente object) => {},
      getId: (Cliente object) => object.id,
      setId: (Cliente object, int id) {
        object.id = id;
      },
      objectToFB: (Cliente object, fb.Builder fbb) {
        final tipoPessoaOffset = fbb.writeString(object.tipoPessoa);
        final nomeRazaoOffset = fbb.writeString(object.nomeRazao);
        final nomeFantasiaOffset = fbb.writeString(object.nomeFantasia);
        final documentoOffset = fbb.writeString(object.documento);
        final inscricaoEstadualOffset = fbb.writeString(
          object.inscricaoEstadual,
        );
        final telefoneOffset = fbb.writeString(object.telefone);
        final whatsappOffset = fbb.writeString(object.whatsapp);
        final emailOffset = fbb.writeString(object.email);
        final cepOffset = fbb.writeString(object.cep);
        final enderecoOffset = fbb.writeString(object.endereco);
        final numeroOffset = fbb.writeString(object.numero);
        final bairroOffset = fbb.writeString(object.bairro);
        final cidadeOffset = fbb.writeString(object.cidade);
        final ufOffset = fbb.writeString(object.uf);
        final referenciaOffset = fbb.writeString(object.referencia);
        final observacoesOffset = fbb.writeString(object.observacoes);
        fbb.startTable(21);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, tipoPessoaOffset);
        fbb.addOffset(2, nomeRazaoOffset);
        fbb.addOffset(3, nomeFantasiaOffset);
        fbb.addOffset(4, documentoOffset);
        fbb.addOffset(5, inscricaoEstadualOffset);
        fbb.addOffset(6, telefoneOffset);
        fbb.addOffset(7, whatsappOffset);
        fbb.addOffset(8, emailOffset);
        fbb.addOffset(9, cepOffset);
        fbb.addOffset(10, enderecoOffset);
        fbb.addOffset(11, numeroOffset);
        fbb.addOffset(12, bairroOffset);
        fbb.addOffset(13, cidadeOffset);
        fbb.addOffset(14, ufOffset);
        fbb.addOffset(15, referenciaOffset);
        fbb.addFloat64(16, object.limiteCredito);
        fbb.addOffset(17, observacoesOffset);
        fbb.addBool(18, object.ativo);
        fbb.addInt64(19, object.criadoEm.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final tipoPessoaParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final nomeRazaoParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final nomeFantasiaParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final documentoParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final inscricaoEstadualParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final telefoneParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final whatsappParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 18, '');
        final emailParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 20, '');
        final cepParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 22, '');
        final enderecoParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 24, '');
        final numeroParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 26, '');
        final bairroParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 28, '');
        final cidadeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 30, '');
        final ufParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 32, '');
        final referenciaParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 34, '');
        final limiteCreditoParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          36,
          0,
        );
        final observacoesParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 38, '');
        final ativoParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          40,
          false,
        );
        final criadoEmParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 42, 0),
          isUtc: true,
        );
        final object = Cliente(
          id: idParam,
          tipoPessoa: tipoPessoaParam,
          nomeRazao: nomeRazaoParam,
          nomeFantasia: nomeFantasiaParam,
          documento: documentoParam,
          inscricaoEstadual: inscricaoEstadualParam,
          telefone: telefoneParam,
          whatsapp: whatsappParam,
          email: emailParam,
          cep: cepParam,
          endereco: enderecoParam,
          numero: numeroParam,
          bairro: bairroParam,
          cidade: cidadeParam,
          uf: ufParam,
          referencia: referenciaParam,
          limiteCredito: limiteCreditoParam,
          observacoes: observacoesParam,
          ativo: ativoParam,
          criadoEm: criadoEmParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [ItemVenda] entity fields to define ObjectBox queries.
class ItemVenda_ {
  /// See [ItemVenda.id].
  static final id = obx.QueryIntegerProperty<ItemVenda>(
    _entities[0].properties[0],
  );

  /// See [ItemVenda.quantidade].
  static final quantidade = obx.QueryIntegerProperty<ItemVenda>(
    _entities[0].properties[1],
  );

  /// See [ItemVenda.precoUnitario].
  static final precoUnitario = obx.QueryDoubleProperty<ItemVenda>(
    _entities[0].properties[2],
  );

  /// See [ItemVenda.produto].
  static final produto = obx.QueryRelationToOne<ItemVenda, Produto>(
    _entities[0].properties[3],
  );

  /// See [ItemVenda.venda].
  static final venda = obx.QueryRelationToOne<ItemVenda, Venda>(
    _entities[0].properties[4],
  );

  /// See [ItemVenda.nomeProduto].
  static final nomeProduto = obx.QueryStringProperty<ItemVenda>(
    _entities[0].properties[5],
  );

  /// See [ItemVenda.precoCustoUnitario].
  static final precoCustoUnitario = obx.QueryDoubleProperty<ItemVenda>(
    _entities[0].properties[6],
  );

  /// See [ItemVenda.precoTipo].
  static final precoTipo = obx.QueryStringProperty<ItemVenda>(
    _entities[0].properties[7],
  );
}

/// [Produto] entity fields to define ObjectBox queries.
class Produto_ {
  /// See [Produto.id].
  static final id = obx.QueryIntegerProperty<Produto>(
    _entities[1].properties[0],
  );

  /// See [Produto.nome].
  static final nome = obx.QueryStringProperty<Produto>(
    _entities[1].properties[1],
  );

  /// See [Produto.estoque].
  static final estoque = obx.QueryIntegerProperty<Produto>(
    _entities[1].properties[2],
  );

  /// See [Produto.precoCusto].
  static final precoCusto = obx.QueryDoubleProperty<Produto>(
    _entities[1].properties[3],
  );

  /// See [Produto.precoVenda].
  static final precoVenda = obx.QueryDoubleProperty<Produto>(
    _entities[1].properties[4],
  );

  /// See [Produto.criadoEm].
  static final criadoEm = obx.QueryDateProperty<Produto>(
    _entities[1].properties[5],
  );

  /// See [Produto.quantidadeMinima].
  static final quantidadeMinima = obx.QueryIntegerProperty<Produto>(
    _entities[1].properties[6],
  );

  /// See [Produto.codigoInterno].
  static final codigoInterno = obx.QueryStringProperty<Produto>(
    _entities[1].properties[7],
  );

  /// See [Produto.descricao].
  static final descricao = obx.QueryStringProperty<Produto>(
    _entities[1].properties[8],
  );

  /// See [Produto.unidade].
  static final unidade = obx.QueryStringProperty<Produto>(
    _entities[1].properties[9],
  );

  /// See [Produto.categoria].
  static final categoria = obx.QueryStringProperty<Produto>(
    _entities[1].properties[10],
  );

  /// See [Produto.subcategoria].
  static final subcategoria = obx.QueryStringProperty<Produto>(
    _entities[1].properties[11],
  );

  /// See [Produto.marca].
  static final marca = obx.QueryStringProperty<Produto>(
    _entities[1].properties[12],
  );

  /// See [Produto.fornecedor].
  static final fornecedor = obx.QueryStringProperty<Produto>(
    _entities[1].properties[13],
  );

  /// See [Produto.fabricante].
  static final fabricante = obx.QueryStringProperty<Produto>(
    _entities[1].properties[14],
  );

  /// See [Produto.codigoBarras].
  static final codigoBarras = obx.QueryStringProperty<Produto>(
    _entities[1].properties[15],
  );

  /// See [Produto.localizacao].
  static final localizacao = obx.QueryStringProperty<Produto>(
    _entities[1].properties[16],
  );

  /// See [Produto.ncm].
  static final ncm = obx.QueryStringProperty<Produto>(
    _entities[1].properties[17],
  );

  /// See [Produto.fotoPath].
  static final fotoPath = obx.QueryStringProperty<Produto>(
    _entities[1].properties[18],
  );

  /// See [Produto.preco1].
  static final preco1 = obx.QueryDoubleProperty<Produto>(
    _entities[1].properties[19],
  );

  /// See [Produto.preco2].
  static final preco2 = obx.QueryDoubleProperty<Produto>(
    _entities[1].properties[20],
  );

  /// See [Produto.preco3].
  static final preco3 = obx.QueryDoubleProperty<Produto>(
    _entities[1].properties[21],
  );
}

/// [Venda] entity fields to define ObjectBox queries.
class Venda_ {
  /// See [Venda.id].
  static final id = obx.QueryIntegerProperty<Venda>(_entities[2].properties[0]);

  /// See [Venda.data].
  static final data = obx.QueryDateProperty<Venda>(_entities[2].properties[1]);

  /// See [Venda.total].
  static final total = obx.QueryDoubleProperty<Venda>(
    _entities[2].properties[2],
  );

  /// See [Venda.custoTotal].
  static final custoTotal = obx.QueryDoubleProperty<Venda>(
    _entities[2].properties[3],
  );

  /// See [Venda.lucroTotal].
  static final lucroTotal = obx.QueryDoubleProperty<Venda>(
    _entities[2].properties[4],
  );

  /// See [Venda.cancelada].
  static final cancelada = obx.QueryBooleanProperty<Venda>(
    _entities[2].properties[5],
  );

  /// See [Venda.status].
  static final status = obx.QueryStringProperty<Venda>(
    _entities[2].properties[6],
  );

  /// See [Venda.numeroOrcamento].
  static final numeroOrcamento = obx.QueryIntegerProperty<Venda>(
    _entities[2].properties[7],
  );

  /// See [Venda.formaPagamento].
  static final formaPagamento = obx.QueryStringProperty<Venda>(
    _entities[2].properties[8],
  );

  /// See [Venda.quantidadeParcelas].
  static final quantidadeParcelas = obx.QueryIntegerProperty<Venda>(
    _entities[2].properties[9],
  );

  /// See [Venda.cliente].
  static final cliente = obx.QueryRelationToOne<Venda, Cliente>(
    _entities[2].properties[10],
  );

  /// See [Venda.tipoEntrega].
  static final tipoEntrega = obx.QueryStringProperty<Venda>(
    _entities[2].properties[11],
  );

  /// See [Venda.valorFrete].
  static final valorFrete = obx.QueryDoubleProperty<Venda>(
    _entities[2].properties[12],
  );

  /// See [Venda.enderecoEntrega].
  static final enderecoEntrega = obx.QueryStringProperty<Venda>(
    _entities[2].properties[13],
  );

  /// See [Venda.observacaoEntrega].
  static final observacaoEntrega = obx.QueryStringProperty<Venda>(
    _entities[2].properties[14],
  );

  /// See [Venda.statusEntrega].
  static final statusEntrega = obx.QueryStringProperty<Venda>(
    _entities[2].properties[15],
  );

  /// see [Venda.itens]
  static final itens = obx.QueryBacklinkToMany<ItemVenda, Venda>(
    ItemVenda_.venda,
  );
}

/// [Cliente] entity fields to define ObjectBox queries.
class Cliente_ {
  /// See [Cliente.id].
  static final id = obx.QueryIntegerProperty<Cliente>(
    _entities[3].properties[0],
  );

  /// See [Cliente.tipoPessoa].
  static final tipoPessoa = obx.QueryStringProperty<Cliente>(
    _entities[3].properties[1],
  );

  /// See [Cliente.nomeRazao].
  static final nomeRazao = obx.QueryStringProperty<Cliente>(
    _entities[3].properties[2],
  );

  /// See [Cliente.nomeFantasia].
  static final nomeFantasia = obx.QueryStringProperty<Cliente>(
    _entities[3].properties[3],
  );

  /// See [Cliente.documento].
  static final documento = obx.QueryStringProperty<Cliente>(
    _entities[3].properties[4],
  );

  /// See [Cliente.inscricaoEstadual].
  static final inscricaoEstadual = obx.QueryStringProperty<Cliente>(
    _entities[3].properties[5],
  );

  /// See [Cliente.telefone].
  static final telefone = obx.QueryStringProperty<Cliente>(
    _entities[3].properties[6],
  );

  /// See [Cliente.whatsapp].
  static final whatsapp = obx.QueryStringProperty<Cliente>(
    _entities[3].properties[7],
  );

  /// See [Cliente.email].
  static final email = obx.QueryStringProperty<Cliente>(
    _entities[3].properties[8],
  );

  /// See [Cliente.cep].
  static final cep = obx.QueryStringProperty<Cliente>(
    _entities[3].properties[9],
  );

  /// See [Cliente.endereco].
  static final endereco = obx.QueryStringProperty<Cliente>(
    _entities[3].properties[10],
  );

  /// See [Cliente.numero].
  static final numero = obx.QueryStringProperty<Cliente>(
    _entities[3].properties[11],
  );

  /// See [Cliente.bairro].
  static final bairro = obx.QueryStringProperty<Cliente>(
    _entities[3].properties[12],
  );

  /// See [Cliente.cidade].
  static final cidade = obx.QueryStringProperty<Cliente>(
    _entities[3].properties[13],
  );

  /// See [Cliente.uf].
  static final uf = obx.QueryStringProperty<Cliente>(
    _entities[3].properties[14],
  );

  /// See [Cliente.referencia].
  static final referencia = obx.QueryStringProperty<Cliente>(
    _entities[3].properties[15],
  );

  /// See [Cliente.limiteCredito].
  static final limiteCredito = obx.QueryDoubleProperty<Cliente>(
    _entities[3].properties[16],
  );

  /// See [Cliente.observacoes].
  static final observacoes = obx.QueryStringProperty<Cliente>(
    _entities[3].properties[17],
  );

  /// See [Cliente.ativo].
  static final ativo = obx.QueryBooleanProperty<Cliente>(
    _entities[3].properties[18],
  );

  /// See [Cliente.criadoEm].
  static final criadoEm = obx.QueryDateProperty<Cliente>(
    _entities[3].properties[19],
  );
}
